# fly.toml app configuration file generated for instaclone-holy-sun-1933 on 2024-08-14T23:44:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'instaclone-holy-sun-1933'
primary_region = 'atl'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
